---
- name: Ensure apache is not installed
  apt:
    name: apache2
    state: absent
  tags: [loadbalancer]
- name: Ensure nginx is not installed
  apt:
    name: nginx
    state: absent
  tags: [loadbalancer]
- name: Ensure haproxy is present or install it
  apt:
    name: haproxy
    state: installed
    update_cache: true
  tags: [loadbalancer]
- name: Enable haproxy
  replace: dest=/etc/default/haproxy
              regexp="ENABLED=0"
              replace="ENABLED=1"
  tags: [loadbalancer]

- name: Install haproxy config
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  tags: [loadbalancer]
  notify:
   - Restart Haproxy